
   File /Users/BachataLu/.Renviron contains invalid line(s)
      "type": "service_account",
      "project_id": "mastering-dbt-394415",
      "private_key_id": "43f5fecdaa9bca2c6181901ae7911d57c391359a",
      "client_email": "lucas-main-account@mastering-dbt-394415.iam.gserviceaccount.com",
      "client_id": "100527903751843177449",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/lucas-main-account%40mastering-dbt-394415.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
      }
   They were ignored

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
[1] "https://bigrquery.r-dbi.org/reference/api-perform.html"
Metadata (Open Data Toronto API):
Rows: 128
Cols: 32
Date: 2023-10-13
Job Status: RUNNING
Job ID: job_1STvdqSLpEEM_3AUY-TcsaGftYg5
Job Creation Time: 2023-10-14 06:41 PM
Job Start Time: 2023-10-14 06:41 PM
======================================================
Warning message:
'bigrquery::insert_upload_job' is deprecated.
Use 'bq_perform_upload' instead.
See help("Deprecated") and help("bigrquery-deprecated"). 
$shelter_extract_mtd
Metadata (Open Data Toronto API):
Rows: 128
Cols: 32
Date: 2023-10-13

$shelter_upload_mtd
Job Status: RUNNING
Job ID: job_1STvdqSLpEEM_3AUY-TcsaGftYg5
Job Creation Time: 2023-10-14 06:41 PM
Job Start Time: 2023-10-14 06:41 PM
======================================================

Error in get_shelter_data(slice = 1) : unused argument (slice = 1)
Calls: %>% -> filter
Execution halted
